when@prod:
    hautelook_alice:
        fixtures_path:
            - fixtures/default

when@dev:
    hautelook_alice:
        fixtures_path:
            - fixtures/default
            - fixtures/dev

when@test:
    hautelook_alice:
        fixtures_path:
            - fixtures/default
            - fixtures/dev
            - fixtures/test
