# Workflow todo
name: CI/CD workflow
on:
  push:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.5'
      - name: Install dependencies
        run: composer install
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Analyzes
        run: make analyze
      - name: Run tests
        run: make jwt-generate test
