# github action that checks code with Rector
name: Rector
on:
    push:

jobs:
    rector:
        runs-on: ubuntu-latest
        if: github.event.pull_request.head.repo.full_name == 'may-english-tchai/api'
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                php-version: 8.2
                coverage: none
            -   uses: "ramsey/composer-install@v2"
            -   run: make rector
